@baseUrl = http://localhost:8080

### Cadastrar aluno
POST {{baseUrl}}/alunos
Content-Type: application/json

{
  "nome" : "Fábio Barbosa",
  "dataNascimento" : "2001-11-16",
  "sexo" : "M",
  "telefone" : "1122334455",
  "celular" : "11911223344",
  "email" : "fabio@email.com",
  "observacao" : "Aluno iniciante",
  "endereco" : "Rua das Flores",
  "numero" : "123",
  "complemento" : "Casa 3",
  "bairro" : "centro",
  "cidade" : "Diadema",
  "estado" : "SP",
  "cep" : "09911575"
}

### Listar alunos
GET {{baseUrl}}/alunos

### Listar alunos por paginação
GET {{baseUrl}}/alunos?page=0&size=10&sort=nome,asc

### Buscar aluno por ID
GET {{baseUrl}}/alunos/1

### Atualizar aluno
PUT {{baseUrl}}/alunos/1
Content-Type: application/json

{
  "nome" : "Fábio Barbosa de Sousa",
  "dataNascimento" : "2001-11-16",
  "sexo" : "M",
  "telefone" : "1122334455",
  "celular" : "11911223344",
  "email" : "fabio@email.com",
  "observacao" : "Aluno intermediário",
  "endereco" : "Rua das Flores",
  "numero" : "123",
  "complemento" : "Casa 3",
  "bairro" : "centro",
  "cidade" : "Diadema",
  "estado" : "SP",
  "cep" : "09911575"
}

### Excluir aluno
DELETE {{baseUrl}}/alunos/1

### Cadastrar aluno inválido
POST {{baseUrl}}/alunos
Content-Type: application/json

{
  "nome" : "",
  "dataNascimento" : "2001-11-16",
  "sexo" : "M",
  "telefone" : "1122334455",
  "celular" : "11911223344",
  "email" : "",
  "observacao" : "Aluno iniciante",
  "endereco" : "Rua das Flores",
  "numero" : "123",
  "complemento" : "Casa 3",
  "bairro" : "centro",
  "cidade" : "Diadema",
  "estado" : "SP",
  "cep" : "09911575"
}

### Listar todos
GET {{baseUrl}}/alunos?page=0&size=10&sort=nome,asc

### Listar por nome
GET {{baseUrl}}/alunos?nome=joao&page=0&size=10&sort=nome,asc

### Listar por cidade
GET {{baseUrl}}/alunos?cidade=Diadema&page=0&size=10&sort=nome,asc

### Listar por estado
GET {{baseUrl}}/alunos?estado=SP&page=0&size=10&sort=nome,asc

### Listar por email
GET {{baseUrl}}/alunos?email=joao@email.com&page=0&size=10&sort=nome,asc

### Faturamento mensal
GET {{baseUrl}}/relatorios/faturamento-mensal

### Alunos por cidade
GET {{baseUrl}}/relatorios/alunos-por-cidade

### Faturas em aberto
GET {{baseUrl}}/relatorios/faturas-em-aberto